apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mfi-account-oracle.fullname" . }}
  labels:
{{ include "mfi-account-oracle.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mfi-account-oracle.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mfi-account-oracle.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if .Values.imagePullCredentials }}
      imagePullSecrets:
        - name: {{ include "mfi-account-oracle.name" . }}-cred
    {{- end }}
      {{- if .Values.init.enabled }}
      initContainers:
        {{- if .Values.init.mysql.enabled }}
        - name: wait-for-mysql
          image: {{ .Values.init.mysql.image }}
          imagePullPolicy: {{ .Values.init.mysql.pullPolicy }}
          command:
            - sh
            - "-c"
            - {{ (.Values.init.mysql.command | replace "$db_user" (print .Values.env.database.dbUser) | replace "$db_password" (print .Values.env.database.dbPass) | replace "$db_host" (print .Values.env.database.dbHost) | replace "$db_database" (print .Values.env.database.dbName) | replace "$db_port" (print .Values.env.database.dbPort) )| quote }}
        {{- end }}
        {{- if .Values.init.migration.enabled }}
        - name: db-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - {{ .Values.init.migration.command }}
          env:
            - name: DATABASE_CONNECTION_HOST
              value: {{ .Values.env.database.dbHost | quote }}
            - name: DATABASE_CONNECTION_PORT
              value: {{ .Values.env.database.dbPort | quote }}
            - name: DATABASE_CONNECTION_USER
              value: {{ .Values.env.database.dbUser | quote }}
            - name: DATABASE_CONNECTION_PASSWORD
              value: {{ .Values.env.database.dbPass | quote }}
            - name: DATABASE_CONNECTION_DATABASE
              value: {{ .Values.env.database.dbName | quote }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LISTEN_ALS_PORT
              value: {{ .Values.env.alsApiListenPort | quote }}
            - name: LISTEN_ADMIN_PORT
              value: {{ .Values.env.adminApiListenPort | quote }}
            - name: LOG_INDENT
              value: {{ .Values.env.logIndent | quote }}
            - name: DATABASE_CONNECTION_HOST
              value: {{ .Values.env.database.dbHost | quote }}
            - name: DATABASE_CONNECTION_PORT
              value: {{ .Values.env.database.dbPort | quote }}
            - name: DATABASE_CONNECTION_USER
              value: {{ .Values.env.database.dbUser | quote }}
            - name: DATABASE_CONNECTION_PASSWORD
              value: {{ .Values.env.database.dbPass | quote }}
            - name: DATABASE_CONNECTION_DATABASE
              value: {{ .Values.env.database.dbName | quote }}
            - name: DATABASE_MIGRATE
              value: {{ .Values.env.database.migrate | quote }}
            - name: ORACLE_TYPE
              value: {{ .Values.env.oracleType | quote }}
            - name: PREFIX_LENGTH
              value: {{ .Values.env.prefixLength | quote }}
          ports:
            - name: alsapiport
              containerPort: {{ .Values.env.alsApiListenPort }}
              protocol: TCP
            - name: adminapiport
              containerPort: {{ .Values.env.adminApiListenPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.env.alsApiListenPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.env.alsApiListenPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
