# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  - name: external-pm4ml-onboarding
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: postman/newman
      tag: latest
      imagePullPolicy: Always
    volumes:
      - name: ext-output
        configMap:
          name: ext-output
      - name: lab-env
        configMap:
          name: lab-env
      - name: test-cert
        configMap:
          name: test-cert
    volumeMounts:
      - mountPath: /data/Lab.postman_environment.json
        subPath: Lab.postman_environment.json
        name: lab-env
        readOnly: true
      - mountPath: /data/onboarding_pm4ml_output.json
        subPath: onboarding_pm4ml_output.json
        name: ext-output
        readOnly: true
      - mountPath: /data/test_cert_list.json
        subPath: test_cert_list.json
        name: test-cert
        readOnly: true
    env:
    - name: ONBOARD_FSP_SCRIPT_URL
      value: "https://raw.githubusercontent.com/pm4ml/pm4ml-test-scripts/v1.4.2/postman/Onboard-Generic-FSP-Central_Ledger.postman_collection.json"
    - name: ORACLE_SETUP_URL
      value: "https://raw.githubusercontent.com/pm4ml/pm4ml-test-scripts/v1.4.2/postman/Account_Alias_Oracle_Setup.postman_collection.json"
    schedule: "* * * * *"
    args:
        - run 
        - https://raw.githubusercontent.com/pm4ml/pm4ml-test-scripts/v1.4.2/postman/Account_Alias_Oracle_Setup.postman_collection.json
        - --insecure
        - -e
        - /data/Lab.postman_environment.json
        - --ssl-client-cert-list 
        - /data/test_cert_list.json
        - -d
        - /data/onboarding_pm4ml_output.json
    serviceAccount:
      name: "external-pm4ml-onboarding"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
    suspend: true
