apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttk.fullname" . }}
  labels:
    {{- include "ttk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      nodePort: {{ .Values.service.api.nodePort }}
      name: api
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http  
  selector:
    {{- include "ttk.selectorLabels" . | nindent 4 }}
